import type { Metadata } from "next";
// import Header from "./components/header/header";
import ClientLayout from "./ClientLayout";
import ClientHead from "./ClientHead";
import Script from "next/script";

import "./globals.css";

export const metadata: Metadata = {
  title: "Lux LP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/globals.css" as="style" />
        <link rel="stylesheet" href="/globals.css" media="print" />
        <link
          rel="preload"
          href="/fonts/Parkinsans-Bold.ttf"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Parkinsans-Medium.ttf"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Parkinsans-Regular.ttf"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Parkinsans-SemiBold.ttf"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <Script id="gtm-head" strategy="afterInteractive">
          {`
        
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5BCR427Z');


          `}
        </Script>
        <ClientHead />
      </head>
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-5BCR427Z"
            height="0"
            width="0"
            style={{
              display: 'none',
              visibility:"hidden"            
            }}
          ></iframe>
        </noscript>

        {/* <Header /> */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
